Add sanity checks to enkive init script.

diff --git a/scripts/enkive b/scripts/enkive
--- a/scripts/enkive
+++ b/scripts/enkive
@@ -9,20 +9,66 @@
 #
 
 
-# system administrator likely wants to edit the following variables
+# SYSTEM ADMINISTRATOR LIKELY WANTS TO MODIFY THE FOLLOWING VARIABLES
 
-ENKIVE_OWNER=$(whoami)
+# user id under which Enkive is run; a good practice is to create a user specifically to run Enkive (e.g., "enkive")
+ENKIVE_OWNER=enkive
+
+# path to top-level Enkive directory; this directory would contain "lib" and "config"
 ENKIVE_HOME=$(pwd)
+
+# path to the jsvc executable file
 JSVC=/usr/local/bin/jsvc
+
+# path to top level of the Java JDK (must be a JDK and not a JRE); should contain "bin", "lib", and "lib/tools.jar"
 JAVA_HOME=/usr/lib/jvm/java-openjdk
+
+# path to directory that contains file "libindri_jni.so"
 INDRI_SO_PATH=/usr/local/lib
+
+
+# TESTING OF THE ABOVE
+
+errors=0
+
+if [ ! -f ${JAVA_HOME}/bin/javac -o ! -f ${JAVA_HOME}/lib/tools.jar ] ;then
+	echo JAVA_HOME is likely set incorrectly.
+	errors=1
+fi
+
+if [ ! -d ${ENKIVE_HOME}/config -o ! -d ${ENKIVE_HOME}/lib ] ;then
+	echo ENKIVE_HOME is likely set incorrectly.
+	errors=1
+fi
+
+if [ ! -f ${INDRI_SO_PATH}/libindri_jni.so ] ;then
+	echo INDRI_SO_PATH is likely set incorrectly.
+	errors=1
+fi
+
+if [ ! -f ${JSVC} ] ;then
+	echo JSVC is likely set incorrectly.
+	errors=1
+fi
+
+if grep --silent "^${ENKIVE_USER}:" /etc/passwd ;then
+	:
+else
+	echo ENKIVE_USER is likely set incorrectly.
+	errors=1
+fi
+
+if [ ${errors} -eq 1 ] ;then
+	echo "Exiting due to error(s). See comments in $0 for guidance."
+	exit 1
+fi
 
 
 # system administrator may not (or may) want to edit the following
 
-ENKIVE_LOG_PATH=$ENKIVE_HOME/data/logs
-ENKIVE_PID_FILE=$ENKIVE_HOME/data/enkive.pid
-ENKIVE_CLASSPATH=$ENKIVE_HOME/enkive.jar:$ENKIVE_HOME/lib/*:$ENKIVE_HOME/lib/spring/*:$ENKIVE_HOME/config
+ENKIVE_LOG_PATH=${ENKIVE_HOME}/data/logs
+ENKIVE_PID_FILE=${ENKIVE_HOME}/data/enkive.pid
+ENKIVE_CLASSPATH=${ENKIVE_HOME}/enkive.jar:${ENKIVE_HOME}/lib/*:${ENKIVE_HOME}/lib/spring/*:${ENKIVE_HOME}/config:${JAVA_HOME}/lib/tools.jar
 
 
 # the following should likely not be edited
